version: '3'
services:
  softnunes-mysql:
    container_name: softnunes-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: db_softnunes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always

  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - softnunes-mysql